# Generated by Django 2.2.1 on 2019-07-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_goods_goods_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=32, verbose_name='商品类型名称')),
                ('type_description', models.TextField(verbose_name='商品类型描述')),
                ('type_image', models.ImageField(upload_to='Buyer/images', verbose_name='商品类型图片')),
            ],
        ),
    ]
