# Generated by Django 2.2.1 on 2019-07-25 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_goodstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Store.GoodsType', verbose_name='商品类型'),
        ),
    ]
